# Generated by Django 5.0.9 on 2024-11-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
