# Generated by Django 5.0.9 on 2024-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_ingrediente_descripcion'),
        ('recetas', '0002_remove_receta_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(to='ingredientes.ingrediente'),
        ),
    ]
