# Generated by Django 5.0.9 on 2024-11-06 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_ingrediente_descripcion'),
        ('recetas', '0003_remove_receta_categoria_remove_receta_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.CreateModel(
            name='IngredientesRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'unique_together': {('ingrediente', 'receta')},
            },
        ),
    ]
