# Generated by Django 5.0.9 on 2024-11-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_alimenticios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planalimenticio',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='planalimenticio',
            name='notas',
        ),
        migrations.AddField(
            model_name='planalimenticio',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planalimenticio',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
